apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels: # Hier stehen die Labels aus der Pod Definition
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env: #Vault oder Secret im nächsten Schritt
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  selector:
    app: demo-voting-app
    name: postgres-pod
  ports:
    - port: 5432
      targetPort: 5432

