apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels: # Hier stehen die Labels aus der Pod Definition
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    app: demo-voting-app
    name: result-app-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005 # <--- Add this line Für den NodePort wird eine Spezielle Portnummer vergeben.
