apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s
  namespace: projekt3
  labels:
    app: nestjs-k8s
spec:
  selector:
    matchLabels:
      app: nestjs-k8s
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: nestjs-k8s
      labels:
        app: nestjs-k8s
      annotations:
        author: ms <marcoschmidl@pm.me>
    spec:
      containers:
        - name: nestjs-k8s
          image: marcoschmidl/nestjs-metrics-k8s-demo
          imagePullPolicy: Always
          ports:
           - name: http
             containerPort: 3000
             protocol: TCP
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi" 
            limits:
              cpu: "1500m"
              memory: "2048Mi"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
        # imagePullSecrets:
        #  - name: docker-hub
