apiVersion: v1
kind: Service
metadata:
  name: nestjs-k8s
  namespace: projekt3
  annotations:
    author: ms <marcoschmidl@pm.me>
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  type: LoadBalancer # or ClusterIP
  selector:
    app: nestjs-k8s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nestjs-k8s
  namespace: projekt3
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: nest
                port:
                  number: 3000
            path: /
            pathType: Prefix
  tls:
    - {}
